"""Initial schema with reports table

Revision ID: 357c3ed043e1
Revises: 
Create Date: 2025-12-18 23:43:25.419561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '357c3ed043e1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('source_version', sa.String(length=50), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('home_city', sa.String(length=255), nullable=False),
    sa.Column('duration_category', sa.String(length=20), nullable=False),
    sa.Column('month_or_season', sa.String(length=50), nullable=False),
    sa.Column('concern', sa.String(length=10), nullable=False),
    sa.Column('skin_type', sa.String(length=20), nullable=True),
    sa.Column('hair_type', sa.String(length=20), nullable=True),
    sa.Column('destination_lat', sa.Float(), nullable=True),
    sa.Column('destination_lon', sa.Float(), nullable=True),
    sa.Column('destination_display_name', sa.String(), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Integer(), nullable=True),
    sa.Column('uv_index', sa.Float(), nullable=True),
    sa.Column('pm25', sa.Float(), nullable=True),
    sa.Column('pm10', sa.Float(), nullable=True),
    sa.Column('no2', sa.Float(), nullable=True),
    sa.Column('o3', sa.Float(), nullable=True),
    sa.Column('aqi', sa.Integer(), nullable=True),
    sa.Column('water_hardness', sa.Integer(), nullable=True),
    sa.Column('water_ph', sa.Float(), nullable=True),
    sa.Column('water_tds', sa.Integer(), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_mock_data', sa.Boolean(), nullable=False),
    sa.Column('missing_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("concern IN ('skin', 'hair')", name='valid_concern'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_concern'), 'reports', ['concern'], unique=False)
    op.create_index(op.f('ix_reports_destination'), 'reports', ['destination'], unique=False)
    op.create_index(op.f('ix_reports_is_mock_data'), 'reports', ['is_mock_data'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_is_mock_data'), table_name='reports')
    op.drop_index(op.f('ix_reports_destination'), table_name='reports')
    op.drop_index(op.f('ix_reports_concern'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
