"""Add water_chlorine field

Revision ID: 526c582e7fa8
Revises: 357c3ed043e1
Create Date: 2025-12-19 22:09:36.459111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '526c582e7fa8'
down_revision: Union[str, Sequence[str], None] = '357c3ed043e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('water_chlorine', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'water_chlorine')
    # ### end Alembic commands ###
